//
// This is automatically generated by the tools.
// DO NOT modify this manually! Edit the corresponding .class files instead!
// Broken Singularity, All Rights Reserved.
//

// BEGIN REGISTRANTS
#ifdef WITH_REGISTRANTS
#ifndef INCLUDED_REGISTRANTS_ENGINE
#define INCLUDED_REGISTRANTS_ENGINE
static void InitRegistrants_Engine()
{
	CObject::StaticAddToAutoInitializeRegistrants( ( CObject* (*)() )&AActor::StaticClass );
	CObject::StaticAddToAutoInitializeRegistrants( ( CObject* (*)() )&CActorComponent::StaticClass );
	CObject::StaticAddToAutoInitializeRegistrants( ( CObject* (*)() )&CSceneComponent::StaticClass );
	CObject::StaticAddToAutoInitializeRegistrants( ( CObject* (*)() )&CPrimitiveComponent::StaticClass );
	CObject::StaticAddToAutoInitializeRegistrants( ( CObject* (*)() )&AStaticMesh::StaticClass );
	CObject::StaticAddToAutoInitializeRegistrants( ( CObject* (*)() )&CStaticMeshComponent::StaticClass );
	CObject::StaticAddToAutoInitializeRegistrants( ( CObject* (*)() )&AAudio::StaticClass );
	CObject::StaticAddToAutoInitializeRegistrants( ( CObject* (*)() )&CAudioComponent::StaticClass );
	CObject::StaticAddToAutoInitializeRegistrants( ( CObject* (*)() )&CSpriteComponent::StaticClass );
	CObject::StaticAddToAutoInitializeRegistrants( ( CObject* (*)() )&ABaseController::StaticClass );
	CObject::StaticAddToAutoInitializeRegistrants( ( CObject* (*)() )&ACharacter::StaticClass );
	CObject::StaticAddToAutoInitializeRegistrants( ( CObject* (*)() )&CCharacterMovementComponent::StaticClass );
	CObject::StaticAddToAutoInitializeRegistrants( ( CObject* (*)() )&ABoxCollision::StaticClass );
	CObject::StaticAddToAutoInitializeRegistrants( ( CObject* (*)() )&CShapeComponent::StaticClass );
	CObject::StaticAddToAutoInitializeRegistrants( ( CObject* (*)() )&CBoxComponent::StaticClass );
	CObject::StaticAddToAutoInitializeRegistrants( ( CObject* (*)() )&ALight::StaticClass );
	CObject::StaticAddToAutoInitializeRegistrants( ( CObject* (*)() )&ADirectionalLight::StaticClass );
	CObject::StaticAddToAutoInitializeRegistrants( ( CObject* (*)() )&CLightComponent::StaticClass );
	CObject::StaticAddToAutoInitializeRegistrants( ( CObject* (*)() )&CDirectionalLightComponent::StaticClass );
	CObject::StaticAddToAutoInitializeRegistrants( ( CObject* (*)() )&CArrowComponent::StaticClass );
	CObject::StaticAddToAutoInitializeRegistrants( ( CObject* (*)() )&APlayerController::StaticClass );
	CObject::StaticAddToAutoInitializeRegistrants( ( CObject* (*)() )&CInputComponent::StaticClass );
	CObject::StaticAddToAutoInitializeRegistrants( ( CObject* (*)() )&APlayerStart::StaticClass );
	CObject::StaticAddToAutoInitializeRegistrants( ( CObject* (*)() )&APointLight::StaticClass );
	CObject::StaticAddToAutoInitializeRegistrants( ( CObject* (*)() )&CPointLightComponent::StaticClass );
	CObject::StaticAddToAutoInitializeRegistrants( ( CObject* (*)() )&ASpotLight::StaticClass );
	CObject::StaticAddToAutoInitializeRegistrants( ( CObject* (*)() )&CSpotLightComponent::StaticClass );
	CObject::StaticAddToAutoInitializeRegistrants( ( CObject* (*)() )&ASprite::StaticClass );
	CObject::StaticAddToAutoInitializeRegistrants( ( CObject* (*)() )&CCameraComponent::StaticClass );
	CObject::StaticAddToAutoInitializeRegistrants( ( CObject* (*)() )&CSphereComponent::StaticClass );
	CObject::StaticAddToAutoInitializeRegistrants( ( CObject* (*)() )&CBaseEngine::StaticClass );
	CObject::StaticAddToAutoInitializeRegistrants( ( CObject* (*)() )&CGameEngine::StaticClass );
	CObject::StaticAddToAutoInitializeRegistrants( ( CObject* (*)() )&CWorld::StaticClass );
	CObject::StaticAddToAutoInitializeRegistrants( ( CObject* (*)() )&Enum::ESpriteType::StaticEnum );
	CObject::StaticAddToAutoInitializeRegistrants( ( CObject* (*)() )&Enum::ECameraProjectionMode::StaticEnum );
}
#endif // !INCLUDED_REGISTRANTS_ENGINE
#endif // WITH_REGISTRANTS
// END REGISTRANTS