/**
 * @file
 * @addtogroup WorldEd World editor
 *
 * Copyright Broken Singularity, All Rights Reserved.
 * Authors: Yehor Pohuliaka (zombiHello)
 */

#ifndef SCRIPTCODEGENERATOR_H
#define SCRIPTCODEGENERATOR_H

#include <vector>

#include "Scripts/ScriptFileContext.h"
#include "Scripts/ScriptSyntaxNode.h"

/**
 * @ingroup WorldEd
 * @brief Byte code generator for compiled script functions
 */
class CScriptCodeGenerator
{
public:
	/**
	 * @brief Constructor
	 * @param InVerbose	Is need to print verbose logs
	 */
	CScriptCodeGenerator( bool InVerbose = false );

	/**
	 * @brief Generate bytecode from syntax tree
	 * 
	 * @param InClassStub		Class stub
	 * @param InSyntaxTree		Syntax tree
	 */
	void GenerateCode( const CScriptClassStub& InClassStub, CScriptSyntaxNode_Base* InSyntaxTree );

	/**
	 * @brief Get generated bytecode
	 * @return Return generated bytecode. If it isn't was generated returns empty array
	 */
	FORCEINLINE const std::vector<byte>& GetBytecode() const
	{
		return bytecode;
	}

private:
	bool					bVerbose;		/**< Is need to print verbose logs */
	std::vector<byte>		bytecode;		/**< Compiled bytecode */
};

#endif // !SCRIPTCODEGENERATOR_H