/**
 * @file
 * @addtogroup WorldEd World editor
 *
 * Copyright Broken Singularity, All Rights Reserved.
 * Authors: Yehor Pohuliaka (zombiHello)
 */

#ifndef SCRIPTCODEGENERATORVISITOR_H
#define SCRIPTCODEGENERATORVISITOR_H

#include "Scripts/ScriptSyntaxNode.h"
#include "Scripts/ScriptSyntaxVisitor.h"
#include "Scripts/ScriptCodeBlock.h"

/**
 * @ingroup WorldEd
 * @brief Code generator
 */
class CScriptCodeGeneratorVisitor : public CScriptSyntaxVisitor
{
public:
	/**
	 * @brief Constructor
	 * @param InClassStub		Class stub where InFunctionStub is
	 * @param InFunctionStub	Function stub where code is
	 */
	CScriptCodeGeneratorVisitor( const CScriptClassStub& InClassStub, const CScriptFunctionStub& InFunctionStub );

	/**
	 * @brief Desutrctor
	 */
	~CScriptCodeGeneratorVisitor();

	/**
	 * @brief Get generated code blocks
	 * @return Return generated code blocks by CScriptSyntaxNode_Base::AcceptVisitor, otherwise NULL
	 */
	FORCEINLINE CScriptCodeBlock* GetCodeBlocks() const
	{
		return codeBlocks;
	}

protected:
	/**
	 * @brief Visit syntax node 'nop'
	 * @param InNode	Node to visit
	 */
	virtual void VisitSyntaxNode_Nop( class CScriptSyntaxNode_Nop* InNode ) override;

	/**
	 * @brief Visit syntax node 'list item'
	 * @param InNode	Node to visit
	 */
	virtual void VisitSyntaxNode_ListItem( class CScriptSyntaxNode_ListItem* InNode ) override;

	/**
	 * @brief Visit syntax node 'ident'
	 * @param InNode	Node to visit
	 */
	virtual void VisitSyntaxNode_Ident( class CScriptSyntaxNode_Ident* InNode ) override;

	/**
	 * @brief Visit syntax node 'function call'
	 * @param InNode	Node to visit
	 */
	virtual void VisitSyntaxNode_FuncCall( class CScriptSyntaxNode_FuncCall* InNode ) override;

	/**
	 * @brief Visit syntax node 'return'
	 * @param InNode	Node to visit
	 */
	virtual void VisitSyntaxNode_Return( class CScriptSyntaxNode_Return* InNode ) override;

	/**
	 * @brief Visit syntax node 'integer constant'
	 * @param InNode	Node to visit
	 */
	virtual void VisitSyntaxNode_IntConst( class CScriptSyntaxNode_IntConst* InNode ) override;

private:
	CScriptCodeBlock*			codeBlocks;		/**< Code blocks which were generated by CScriptSyntaxNode_Base::AcceptVisitor */
	const CScriptClassStub&		classStub;		/**< Class stub where functionStub is */
	const CScriptFunctionStub&	functionStub;	/**< Function stub where code is */
};

#endif // !SCRIPTCODEGENERATORVISITOR_H