//
// This is automatically generated by the tools.
// DO NOT modify this manually! Edit the corresponding .class files instead!
// Broken Singularity, All Rights Reserved.
//

// BEGIN REGISTRANTS
#ifdef WITH_REGISTRANTS
#ifndef INCLUDED_REGISTRANTS_PHYSICS
#define INCLUDED_REGISTRANTS_PHYSICS
static void InitRegistrants_Physics()
{
	CObject::StaticAddToAutoInitializeRegistrants( ( CObject* (*)() )&CollisionProfile::StaticStruct );
	CObject::StaticAddToAutoInitializeRegistrants( ( CObject* (*)() )&Enum::ECollisionChannel::StaticEnum );
	CObject::StaticAddToAutoInitializeRegistrants( ( CObject* (*)() )&Enum::ECollisionResponse::StaticEnum );
}
#endif // !INCLUDED_REGISTRANTS_PHYSICS
#endif // WITH_REGISTRANTS
// END REGISTRANTS