/*=========================================
 C++ class definitions exported from AngelScript.
 This is automatically generated by the tools.
 DO NOT modify this manually! Edit the corresponding .as files instead!
 BSOD-Games, All Rights Reserved.
==========================================*/

#pragma once

#include <angelscript.h>
#include "Scripts/ScriptVar.h"
#include "Scripts/ScriptObject.h"

// ----------------------------------
// FUNCTIONS
// ----------------------------------

void execEmptyFile()
{
	asIScriptEngine*		scriptEngine = GScriptEngine->GetASScriptEngine();
	asIScriptContext*		scriptContext = scriptEngine->CreateContext();
	check( scriptContext );

	asIScriptFunction*		function = scriptEngine->GetModule( "Core" )->GetFunctionByIndex( 0 );
	check( function );

	int32	result = scriptContext->Prepare( function );
	check( result >= 0 );

	result = scriptContext->Execute();
	check( result >= 0 );
	scriptContext->Release();
}

// ----------------------------------
// INITIALIZATION MACROS
// ----------------------------------

#define DECLARATE_GLOBALVALUES_SCRIPTMODULE_Core

// ----------------------------------
// INITIALIZATION FUNCTION
// ----------------------------------

void InitScriptModule_Core()
{
}