//
// This is automatically generated by the tools.
// DO NOT modify this manually! Edit the corresponding .class files instead!
// Broken Singularity, All Rights Reserved.
//

// BEGIN REGISTRANTS
#ifdef WITH_REGISTRANTS
#ifndef INCLUDED_REGISTRANTS_ELEOTGAME
#define INCLUDED_REGISTRANTS_ELEOTGAME
static void InitRegistrants_EleotGame()
{
	CObject::StaticAddToAutoInitializeRegistrants( ( CObject* (*)() )&AELPlayerCharacter::StaticClass );
	CObject::StaticAddToAutoInitializeRegistrants( ( CObject* (*)() )&AELPlayerController::StaticClass );
}
#endif // !INCLUDED_REGISTRANTS_ELEOTGAME
#endif // WITH_REGISTRANTS
// END REGISTRANTS