//
// This is automatically generated by the tools.
// DO NOT modify this manually! Edit the corresponding .class files instead!
// Broken Singularity, All Rights Reserved.
//

// BEGIN REGISTRANTS
#ifdef WITH_REGISTRANTS
#ifndef INCLUDED_REGISTRANTS_WORLDED
#define INCLUDED_REGISTRANTS_WORLDED
static void InitRegistrants_WorldEd()
{
	CObject::StaticAddToAutoInitializeRegistrants( ( CObject* (*)() )&CBaseCommandlet::StaticClass );
	CObject::StaticAddToAutoInitializeRegistrants( ( CObject* (*)() )&CCookPackagesCommandlet::StaticClass );
	CObject::StaticAddToAutoInitializeRegistrants( ( CObject* (*)() )&CScriptCompilerCommandlet::StaticClass );
	CObject::StaticAddToAutoInitializeRegistrants( ( CObject* (*)() )&CFixupRedirectsCommandlet::StaticClass );
	CObject::StaticAddToAutoInitializeRegistrants( ( CObject* (*)() )&CEditorEngine::StaticClass );
}
#endif // !INCLUDED_REGISTRANTS_WORLDED
#endif // WITH_REGISTRANTS
// END REGISTRANTS