/*=========================================
 C++ class definitions exported from AngelScript.
 This is automatically generated by the tools.
 DO NOT modify this manually! Edit the corresponding .as files instead!
 BSOD-Games, All Rights Reserved.
==========================================*/

#include <angelscript.h>

// ----------------------------------
// FUNCTIONS
// ----------------------------------

int32 execGameInit()
{
	asIScriptContext*		scriptContext = GScriptEngine->GetASScriptEngine()->CreateContext();
	check( scriptContext );

	asIScriptFunction*		function = GScriptEngine->GetASScriptEngine()->GetModule( "TestbedGame" )->GetFunctionByIndex( 0 );
	check( function );

	int32	result = scriptContext->Prepare( function );
	check( result >= 0 );

	result = scriptContext->Execute();
	check( result >= 0 );

	int32		returnValue = scriptContext->GetReturnDWord();
	scriptContext->Release();
	return returnValue;
}
