/**
 * ************************************************************
 *                  This file is part of:
 *                      LIFEENGINE
 *          https://github.com/zombihello/lifeEngine
 * ************************************************************
 * Copyright (C) 2024 Yehor Pohuliaka.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include "pch_shadercompile.h"
#include "tools/shadercompile/shader_cppclass_generator.h"

/*
==================
CShaderCppClassGenerator::Generate
==================
*/
void CShaderCppClassGenerator::Generate( const Shader& shader )
{
	// Generate C++ header
	buffer += "//\n";
	buffer += "// This is automatically generated by shadercompile\n";
	buffer += "// DO NOT modify this manually! Edit the corresponding .makefile instead!\n";
	buffer += "// Copyright (C) 2024 Yehor Pohuliaka\n";
	buffer += "//\n\n";

	// Generate class name from base name of shader source file and the one type
	std::string		className;
	{
		// Convert shader type to string
		const achar*	pShaderTypeName = "";
		ConvShaderTypeToString( shader.type, pShaderTypeName );

		// Get base name from shader source file
		std::string		fileBaseName;
		L_GetFileBaseName( shader.source, fileBaseName, false );

		// Get class name
		className = L_Sprintf( "C_%s_%s_Index", fileBaseName.c_str(), pShaderTypeName );
	}

	// Generate C++ class header	
	buffer += L_Sprintf( "class %s\n", className.c_str() );
	buffer += "{\n";

	// Generate for each shader flag a var and set function of the one
	for ( uint32 index = 0, count = ( uint32 )shader.flags.size(); index < count; ++index )
	{
		const ShaderFlag&		shaderFlag = shader.flags[index];
		buffer += "\t//\n";
		buffer += L_Sprintf( "\t// Shader flag '%s' with range [%i;%i]\n", shaderFlag.name.c_str(), shaderFlag.min, shaderFlag.max );
		buffer += "\t//\n";
		GenerateVar( shaderFlag );
		buffer += "\n\n";
	}

	// Generate class constructor
	buffer += "\t//\n";
	buffer += "\t// Class constructor\n";
	buffer += "\t//\n";
	GenerateConstructor( className.c_str(), shader );
	buffer += "\n\n";

	// Generate GetIndex function
	buffer += "\t//\n";
	buffer += "\t// Calculate shader index for the flags combination\n";
	buffer += "\t//\n";
	GenerateGetIndexFunc( shader );
	buffer += "\n";

	// Generate C++ class footer
	buffer += "};\n";
}

/*
==================
CShaderCppClassGenerator::GenerateVar
==================
*/
void CShaderCppClassGenerator::GenerateVar( const ShaderFlag& shaderFlag )
{
	// Generate variables
	buffer += "private:\n";
	buffer += L_Sprintf( "\tuint32 %s;\n", shaderFlag.name.c_str() );
	buffer += "#if DEBUG\n";
	buffer += L_Sprintf( "\tbool b%s;\n", shaderFlag.name.c_str() );
	buffer += "#endif // DEBUG\n";

	// Generate set function
	buffer += "public:\n";

	// Uint32 version
	buffer += L_Sprintf( "\tvoid Set%s( uint32 value )\n", shaderFlag.name.c_str() );
	buffer += "\t{\n";
	buffer += L_Sprintf( "\t\tAssert( value >= %i && value <= %i );\n", shaderFlag.min, shaderFlag.max );
	buffer += L_Sprintf( "\t\t%s = value;\n", shaderFlag.name.c_str() );
	buffer += "#if DEBUG\n";
	buffer += L_Sprintf( "\t\tb%s = true;\n", shaderFlag.name.c_str() );
	buffer += "#endif // DEBUG\n";
	buffer += "\t}";

	// Bool version (only if 0 and 1 in our range)
	if ( 0 >= shaderFlag.min && 0 <= shaderFlag.max && 1 >= shaderFlag.min && 1 <= shaderFlag.max )
	{
		buffer += L_Sprintf( "\n\n\tvoid Set%s( bool bValue )\n", shaderFlag.name.c_str() );
		buffer += "\t{\n";
		buffer += L_Sprintf( "\t\t%s = bValue ? 1 : 0;\n", shaderFlag.name.c_str() );
		buffer += "#if DEBUG\n";
		buffer += L_Sprintf( "\t\tb%s = true;\n", shaderFlag.name.c_str() );
		buffer += "#endif // DEBUG\n";
		buffer += "\t}";
	}
}

/*
==================
CShaderCppClassGenerator::GenerateVar
==================
*/
void CShaderCppClassGenerator::GenerateConstructor( const achar* pClassName, const Shader& shader )
{
	buffer += "public:\n";
	buffer += L_Sprintf( "\t%s()\n", pClassName );
	if ( !shader.flags.empty() )
	{
		for ( uint32 index = 0, count = ( uint32 )shader.flags.size(); index < count; ++index )
		{
			const ShaderFlag&	shaderFlag = shader.flags[index];
			buffer				+= L_Sprintf( "\t\t%s", index == 0 ? ": " : ", " );
			buffer				+= L_Sprintf( "%s( %i )\n", shaderFlag.name.c_str(), shaderFlag.bSetDefault ? shaderFlag.defaultValue : shaderFlag.min );
			buffer				+= "#if DEBUG\n";
			buffer				+= L_Sprintf( "\t\t, b%s( %s )\n", shaderFlag.name.c_str(), shaderFlag.bSetDefault ? "true" : "false" );
			buffer				+= "#endif // DEBUG\n";
		}
	}
	buffer += "\t{}";
}

/*
==================
CShaderCppClassGenerator::GenerateGetIndexFunc
==================
*/
void CShaderCppClassGenerator::GenerateGetIndexFunc( const Shader& shader )
{
	buffer += "public:\n";
	buffer += "\tuint32 GetIndex() const\n";
	buffer += "\t{\n";

	// Generate assert to make sure that we are setting all of the combination vars
	if ( !shader.flags.empty() )
	{
		buffer += "\t\t// Asserts to make sure that we are setting all of the combination vars\n";
		buffer += "#if DEBUG\n";
		buffer += L_Sprintf( "\t\tbool bAllVarsDefined = " );
		
		for ( uint32 index = 0, count = ( uint32 )shader.flags.size(); index < count; ++index )
		{
			const ShaderFlag&	shaderFlag = shader.flags[index];
			buffer += L_Sprintf( "b%s", shaderFlag.name.c_str() );
			if ( index + 1 < count )
			{
				buffer += " && ";
			}
			else
			{
				buffer += ";\n";
			}
		}

		buffer += "\t\tAssert( bAllVarsDefined );\n";
		buffer += "#endif // DEBUG\n";
	}
	
	// Generate code of calculation shader index for the flags combination 
	buffer += "\t\treturn ";
	if ( !shader.flags.empty() )
	{
		uint32	scale = 1;
		for ( uint32 index = 0, count = ( uint32 )shader.flags.size(); index < count; ++index )
		{
			const ShaderFlag&	shaderFlag = shader.flags[index];
			buffer	+= L_Sprintf( "( %i * %s ) + ", scale, shaderFlag.name.c_str() );
			scale	*= shaderFlag.max - shaderFlag.min + 1;
		}
	}

	buffer += "0;\n\t}";
}