/**
 * ************************************************************
 *                  This file is part of:
 *                      LIFEENGINE
 *          https://github.com/zombihello/lifeEngine
 * ************************************************************
 * Copyright (C) 2024 Yehor Pohuliaka.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

#include "pch_shadercompile.h"
#include "tools/shadercompile/vf_cppclass_generator.h"

// Table of C++ vertex factory type names
static const achar* s_pCppVFTypeNames[] =
{
	"VERTEXFACTORY_TYPE_SIMPLEELEMENT"		// VERTEXFACTORY_TYPE_SIMPLEELEMENT
};
static_assert( VERTEXFACTORY_NUM_TYPES == ARRAYSIZE( s_pCppVFTypeNames ), "Array size 's_pCppVFTypeNames' must be equal to VERTEXFACTORY_NUM_TYPES" );

/*
==================
ConvVFTypeToCppString
==================
*/
static void ConvVFTypeToCppString( EVertexFactoryType vfType, std::string& cppVFTypeName )
{
	Assert( vfType < VERTEXFACTORY_NUM_TYPES );
	cppVFTypeName = s_pCppVFTypeNames[( uint32 )vfType];
}


/*
==================
CVFCppClassGenerator::Generate
==================
*/
void CVFCppClassGenerator::Generate( const VertexFactory& vertexFactory, EVertexFactoryType vfType )
{
	// Generate C++ header
	buffer += "//\n";
	buffer += "// This is automatically generated by shadercompile\n";
	buffer += "// DO NOT modify this manually! Edit the corresponding .makefile instead!\n";
	buffer += "// Copyright (C) 2024 Yehor Pohuliaka\n";
	buffer += "//\n\n";
	
	// Convert vertex factory type to string
	std::string		cppVFTypeName;
	ConvVFTypeToCppString( vfType, cppVFTypeName );

	// Generate C++ class header	
	buffer += "//\n";
	buffer += L_Sprintf( "// Meta type for '%s'\n", cppVFTypeName.c_str() );
	buffer += "//\n";
	buffer += L_Sprintf( "class C_%s_MetaType\n", cppVFTypeName.c_str() );
	buffer += "{\n";
	buffer += "public:\n";

	// Generate function GetType
	buffer += "\tstatic EVertexFactoryType GetType()\n";
	buffer += "\t{\n";
	buffer += L_Sprintf( "\t\treturn %s;\n", cppVFTypeName.c_str() );
	buffer += "\t}\n\n";

	// Generate function SupportsInstancing
	buffer += "\tstatic bool SupportsInstancing()\n";
	buffer += "\t{\n";
	buffer += L_Sprintf( "\t\treturn %s;\n", vertexFactory.bSupportsInstancing ? "true" : "false" );
	buffer += "\t}\n\n";

	// Generate function GetInstanceStreamIndex
	buffer += "\tstatic uint32 GetInstanceStreamIndex()\n";
	buffer += "\t{\n";
	buffer += L_Sprintf( "\t\treturn %i;\n", vertexFactory.instanceStreamIndex );
	buffer += "\t}\n";

	// Generate C++ class footer
	buffer += "};\n";
}